# NexT主题配置文件
# 详细配置文档: https://theme-next.js.org/docs/

# 主题外观设置
scheme: Muse  # Muse | Mist | Pisces | Gemini

# 网站图标
favicon:
  small: /images/favicon-16x16.png
  medium: /images/favicon-32x32.png
  apple_touch_icon: /images/apple-touch-icon.png

# 菜单配置
menu:
  home: / || fa fa-home
  about: /about/ || fa fa-user
  tags: /tags/ || fa fa-tags
  categories: /categories/ || fa fa-th
  archives: /archives/ || fa fa-archive
  #schedule: /schedule/ || fa fa-calendar
  #sitemap: /sitemap.xml || fa fa-sitemap
  #commonweal: /404/ || fa fa-heartbeat

# 菜单设置
menu_settings:
  icons: true
  badges: false

# 侧边栏设置
sidebar:
  position: left
  display: post
  padding: 18
  offset: 12

# 头像设置
avatar:
  url: /images/avatar.gif
  rounded: false
  rotated: false

# 社交链接
social:
  GitHub: https://github.com/yourname || fab fa-github
  E-Mail: mailto:yourname@gmail.com || fa fa-envelope
  #Weibo: https://weibo.com/yourname || fab fa-weibo
  #Twitter: https://twitter.com/yourname || fab fa-twitter
  #FB Page: https://www.facebook.com/yourname || fab fa-facebook
  #StackOverflow: https://stackoverflow.com/yourname || fab fa-stack-overflow
  #YouTube: https://youtube.com/yourname || fab fa-youtube
  #Instagram: https://instagram.com/yourname || fab fa-instagram
  #Skype: skype:yourname?call|chat || fab fa-skype

social_icons:
  enable: true
  icons_only: false
  transition: false

# 文章元信息
post_meta:
  item_text: true
  created_at: true
  updated_at:
    enable: true
    another_day: true
  categories: true

# 文章编辑链接
post_edit:
  enable: false
  url: https://github.com/user-name/repo-name/tree/branch-name/subdirectory-name/ # Link for view source
  # url: https://github.com/user-name/repo-name/edit/branch-name/subdirectory-name/ # Link for fork & edit

# 代码高亮主题
codeblock:
  theme:
    light: default
    dark: stackoverflow-dark
  prism:
    light: prism
    dark: prism-dark
  copy_button:
    enable: true
    show_result: false
    style: flat

# 目录设置
toc:
  enable: true
  number: true
  wrap: false
  expand_all: false
  max_depth: 6

# 阅读进度
reading_progress:
  enable: false
  position: top
  color: "#37c6c0"
  height: 3px

# 书签
bookmark:
  enable: false
  color: "#222"
  save: auto

# GitHub横幅
github_banner:
  enable: false
  permalink: https://github.com/yourname
  title: Follow me on GitHub

# 字体设置
font:
  enable: false
  host: https://fonts.googleapis.com
  global:
    external: true
    family: Lato
    size:
  title:
    external: true
    family:
    size:
  headings:
    external: true
    family:
    size:
  posts:
    external: true
    family:
  logo:
    external: true
    family:
    size:
  codes:
    external: true
    family:

# 搜索服务
local_search:
  enable: true
  trigger: auto
  top_n_per_article: 1
  unescape: false
  preload: false

# 评论系统 - Gitalk
gitalk:
  enable: false
  github_id: # GitHub repo owner
  repo: # Repository name to store issues
  client_id: # GitHub Application Client ID
  client_secret: # GitHub Application Client Secret
  admin_user: # GitHub repo owner and collaborators, only these guys can initialize gitHub issues
  distraction_free_mode: true # Facebook-like distraction free mode
  # When the official proxy is not available, you can change it to your own proxy address
  proxy: https://cors-anywhere.azm.workers.dev/https://github.com/login/oauth/access_token # This is official proxy address
  # Gitalk's display language depends on user's browser or system environment
  # If you want everyone visiting your site to see a uniform language, you can set a force language value
  # Available values: en | es-ES | fr | ru | zh-CN | zh-TW
  language:

# 数学公式支持
math:
  every_page: false
  mathjax:
    enable: false
    tags: none
  katex:
    enable: false
    copy_tex: false

# Mermaid图表
mermaid:
  enable: false
  theme:
    light: default
    dark: dark

# 页脚设置
footer:
  since: 2025
  icon:
    name: fa fa-heart
    animated: false
    color: "#ff0000"
  copyright:
  powered: true

# 创意共享许可证
creative_commons:
  license: by-nc-sa
  sidebar: false
  post: false
  language: